name = "glcipes"
license = "MIT"
licenselink = "https://github.com/nooneischgl/glecipes/blob/main/LICENSE"
description = "A recipe theme for Hugo"
homepage = "https://github.com/seanlane/gochowdown"
tags = ["recipes", "cooking", "responsive", "clean"]
features = ["analytics", "favicon"]
min_version = "0.58"

[author]
  name = "Chase Gleason"
  homepage = "https://schasegleason.me"
